### ISSUE TITLE
Add setting to disable automatic VCS tags

### ISSUE THREAD

**Issue by redclov3r** [HypeMC/versioning-bundle#1]
Hi there,

I really like the git integration of this bundle, but I do my tagging a little differently. For that it would be really nice to disable the whole tagging feature by a configuration flag. I know that i could replace the default `GitHandler` by a custom one with an empty `tag()` method but that would still not get rid of the prompt when increasing.

I'd propose a configuration value `bizkit_versioning.vcs.auto_tag` with a default value of `true`. When set to `false`, the whole tagging step will be skipped inside of `commitAndTag()`.

If you think that's sensible, let me know. I can work on a PR.

Best regards.

**Comment by HypeMC** [comment]
@redclov3r Hi! First of all, thanks for using my bundle. It’s great to know someone's finding it useful! :smile: 

Your proposal sounds reasonable to me. If you're willing to work on a PR, I'll gladly merge it.
