### ISSUE TITLE
create the package config via recipe or endroid/installer  

### ISSUE THREAD

**Issue by tacman** [HypeMC/versioning-bundle#4]
My first instinct when playing with this bundle was "I want semantic versioning, not incremental".  

So I expect a package config to already be created.  

I don't care for the Symfony recibes-contrib, but I've found that the endroid/installer package works really well for this.  I can make a PR for endroid if you're okay with that.

Absent a config file, I use the config:dump-reference, which is how I noticed that it generated an invalid file, which you fixed in #3 .

**Comment by HypeMC** [comment]
@tacman Hi! First of all, thanks for using my bundle.

I've created a recipe. Feedback is welcome if you think it needs improvement: https://github.com/symfony/recipes-contrib/pull/1718

**Comment by tacman** [comment]
Great!  I'll try it once it's approved.

**Comment by HypeMC** [comment]
The recipe has been merged.
